#!/usr/bin/env node

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

function readStdin() {
  return new Promise((resolve) => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', (chunk) => { data += chunk; });
    process.stdin.on('end', () => resolve(data));
  });
}

function argValue(args, name) {
  const idx = args.indexOf(name);
  return idx >= 0 ? args[idx + 1] || '' : '';
}

function readSessionId(filePath) {
  try {
    const firstLine = fs.readFileSync(filePath, 'utf8').split('\n').find(Boolean) || '';
    const header = JSON.parse(firstLine);
    return header?.type === 'session' ? header.id || '' : '';
  } catch {
    return '';
  }
}

function resolveSessionFile(sessionDir, sessionArg, sessionId) {
  if (sessionArg) {
    if (path.isAbsolute(sessionArg) || sessionArg.includes(path.sep) || sessionArg.endsWith('.jsonl')) {
      return path.resolve(sessionArg);
    }
    return path.join(sessionDir, `${sessionArg}.jsonl`);
  }
  return path.join(sessionDir, `${sessionId}.jsonl`);
}

function appendJsonl(filePath, entry) {
  fs.appendFileSync(filePath, `${JSON.stringify(entry)}\n`);
}

function emit(entry) {
  process.stdout.write(`${JSON.stringify(entry)}\n`);
}

(async function main() {
  const args = process.argv.slice(2);
  const sessionDir = argValue(args, '--session-dir') || process.cwd();
  const sessionArg = argValue(args, '--session');
  const modelArg = argValue(args, '--model');
  const input = (await readStdin()).trim();
  const imageCount = args.filter((arg) => String(arg || '').startsWith('@')).length;

  fs.mkdirSync(sessionDir, { recursive: true });

  const existingFile = sessionArg ? resolveSessionFile(sessionDir, sessionArg, sessionArg) : '';
  const existingId = existingFile && fs.existsSync(existingFile) ? readSessionId(existingFile) : '';
  const sessionId = existingId || (sessionArg && !sessionArg.endsWith('.jsonl') && !sessionArg.includes(path.sep) ? sessionArg : crypto.randomUUID());
  const sessionFile = resolveSessionFile(sessionDir, sessionArg, sessionId);
  fs.mkdirSync(path.dirname(sessionFile), { recursive: true });

  const now = new Date().toISOString();
  if (!fs.existsSync(sessionFile)) {
    appendJsonl(sessionFile, { type: 'session', version: 3, id: sessionId, cwd: process.cwd() });
    if (modelArg) {
      const parts = modelArg.split('/');
      appendJsonl(sessionFile, {
        type: 'model_change',
        timestamp: now,
        provider: parts.length > 1 ? parts[0] : '',
        modelId: parts.length > 1 ? parts.slice(1).join('/') : modelArg,
      });
    }
  }

  emit({ type: 'session', version: 3, id: sessionId, cwd: process.cwd() });

  appendJsonl(sessionFile, {
    type: 'message',
    timestamp: now,
    message: {
      role: 'user',
      content: [{ type: 'text', text: input }],
    },
  });

  const isInitPrompt = input === '/init' || input.includes('cc-web\'s /init for a Pi session');
  if (isInitPrompt) {
    fs.writeFileSync(path.join(process.cwd(), 'AGENTS.md'), '# AGENTS.md\n\nGenerated by mock Pi /init.\n');
  }

  const runPwd = /pwd/i.test(input);
  const toolCallId = runPwd ? 'pi_tool_pwd' : '';
  if (runPwd) {
    emit({
      type: 'tool_execution_start',
      toolCallId,
      toolName: 'bash',
      args: { command: '/bin/bash -lc pwd' },
    });
    emit({
      type: 'tool_execution_end',
      toolCallId,
      toolName: 'bash',
      args: { command: '/bin/bash -lc pwd' },
      result: {
        content: [{ type: 'text', text: '/tmp/mock-pi\n' }],
        details: { exitCode: 0 },
      },
    });
  }

  const responseText = input === '/compact'
    ? 'Pi compact finished.'
    : isInitPrompt
      ? 'Pi init finished.'
      : `Pi mock handled (${imageCount} image): ${input}`;
  const mid = `msg_${crypto.randomUUID()}`;
  const partial = responseText.slice(0, Math.max(1, Math.floor(responseText.length / 2)));
  const content = [{ type: 'text', text: responseText }];
  if (runPwd) {
    content.push({
      type: 'toolCall',
      id: toolCallId,
      name: 'bash',
      arguments: { command: '/bin/bash -lc pwd' },
    });
  }

  emit({
    type: 'message_update',
    message: {
      id: mid,
      role: 'assistant',
      content: [{ type: 'text', text: partial }],
    },
  });
  emit({
    type: 'message_end',
    message: {
      id: mid,
      role: 'assistant',
      content,
      usage: {
        input: 12,
        cacheRead: 3,
        output: 8,
        cost: { total: 0.001 },
      },
    },
  });
  appendJsonl(sessionFile, {
    type: 'message',
    timestamp: new Date().toISOString(),
    message: {
      role: 'assistant',
      content,
      usage: {
        input: 12,
        cacheRead: 3,
        output: 8,
        cost: { total: 0.001 },
      },
    },
  });
  if (runPwd) {
    appendJsonl(sessionFile, {
      type: 'message',
      timestamp: new Date().toISOString(),
      message: {
        role: 'toolResult',
        toolCallId,
        content: [{ type: 'text', text: '/tmp/mock-pi\n' }],
      },
    });
  }
  emit({ type: 'agent_end', sessionId });
})();
